// Builds src/data/usmap.ts: the 48 contiguous states (DC drawn with Maryland) as SVG paths,
// from the US Census boundaries in us-atlas (already projected, Albers USA, 975 x 610).
//
//   node scripts/build-usmap.mjs
//
// Also works out which states share a border (the dealer network grows state by state
// into neighbours) and gives neighbours different paper colours, as period atlases did.
import { createRequire } from 'module';
import { writeFileSync } from 'fs';

const require = createRequire(import.meta.url);
const topo = require('us-atlas/states-albers-10m.json');
const { feature, merge, neighbors } = require('topojson-client');
const { presimplify, simplify } = require('topojson-simplify');
const { geoPath } = require('d3-geo');

const FIPS = {
  '01': 'AL', '04': 'AZ', '05': 'AR', '06': 'CA', '08': 'CO', '09': 'CT', '10': 'DE', '11': 'DC', '12': 'FL',
  '13': 'GA', '16': 'ID', '17': 'IL', '18': 'IN', '19': 'IA', '20': 'KS', '21': 'KY', '22': 'LA', '23': 'ME',
  '24': 'MD', '25': 'MA', '26': 'MI', '27': 'MN', '28': 'MS', '29': 'MO', '30': 'MT', '31': 'NE', '32': 'NV',
  '33': 'NH', '34': 'NJ', '35': 'NM', '36': 'NY', '37': 'NC', '38': 'ND', '39': 'OH', '40': 'OK', '41': 'OR',
  '42': 'PA', '44': 'RI', '45': 'SC', '46': 'SD', '47': 'TN', '48': 'TX', '49': 'UT', '50': 'VT', '51': 'VA',
  '53': 'WA', '54': 'WV', '55': 'WI', '56': 'WY',
};

// Simplify in screen space: drop points whose triangle is under ~0.6 px².
const simple = simplify(presimplify(topo), 0.6);
const geoms = simple.objects.states.geometries.filter((g) => FIPS[g.id]);
const codeOf = (g) => FIPS[g.id];

const path = geoPath(null).digits(1);
const shapes = {};
const byCode = {};
for (const g of geoms) (byCode[codeOf(g)] ??= []).push(g);
// Maryland takes in the District of Columbia.
byCode.MD.push(...byCode.DC);
delete byCode.DC;

/** Islands smaller than ~3 px² vanish at this scale anyway. */
function dropSpecks(geo) {
  const g = geo.geometry ?? geo;
  if (g.type !== 'MultiPolygon') return geo;
  const polys = g.coordinates.filter((p) => path.area({ type: 'Polygon', coordinates: p }) >= 3);
  return { type: 'Feature', geometry: { type: 'MultiPolygon', coordinates: polys } };
}

for (const [code, gs] of Object.entries(byCode)) {
  const geo = dropSpecks(gs.length === 1 ? feature(simple, gs[0]) : { type: 'Feature', geometry: merge(simple, gs) });
  shapes[code] = { d: path(geo), label: path.centroid(geo).map((v) => Math.round(v)), area: Math.round(path.area(geo)) };
}

// Neighbours: states that share a border line (touching at a point, like the Four Corners, does not count).
const nb = neighbors(geoms);
const near = {};
geoms.forEach((g, i) => {
  const a = codeOf(g) === 'DC' ? 'MD' : codeOf(g);
  for (const j of nb[i]) {
    const b = codeOf(geoms[j]) === 'DC' ? 'MD' : codeOf(geoms[j]);
    if (a !== b) (near[a] ??= new Set()).add(b);
  }
});

// Five atlas tints, neighbours never alike (greedy, biggest states first).
const codes = Object.keys(shapes).sort((a, b) => near[b].size - near[a].size || shapes[b].area - shapes[a].area);
const tint = {};
for (const c of codes) {
  const used = new Set([...near[c]].map((n) => tint[n]).filter((v) => v !== undefined));
  let t = 0;
  while (used.has(t)) t++;
  tint[c] = t;
}

const nation = path(dropSpecks(merge(simple, geoms)));

// Cities on the map (lon, lat): the places a car company could start from, and the big
// towns of the period that make the map readable. Same projection as us-atlas.
const { geoAlbersUsa } = require('d3-geo');
const proj = geoAlbersUsa().scale(1300).translate([487.5, 305]);
const CITIES = {
  detroit: [-83.05, 42.33], cleveland: [-81.69, 41.5], chicago: [-87.63, 41.88], hartford: [-72.68, 41.76],
  newyork: [-74.01, 40.71], stlouis: [-90.2, 38.63], losangeles: [-118.24, 34.05], indianapolis: [-86.16, 39.77],
  boston: [-71.06, 42.36], philadelphia: [-75.17, 39.95], baltimore: [-76.61, 39.29], pittsburgh: [-79.99, 40.44],
  buffalo: [-78.88, 42.89], cincinnati: [-84.51, 39.1], milwaukee: [-87.91, 43.04], minneapolis: [-93.27, 44.98],
  kansascity: [-94.58, 39.1], neworleans: [-90.07, 29.95], atlanta: [-84.39, 33.75], denver: [-104.99, 39.74],
  sanfrancisco: [-122.42, 37.77], seattle: [-122.33, 47.61], portland: [-122.68, 45.52], dallas: [-96.8, 32.78],
  houston: [-95.37, 29.76], omaha: [-95.94, 41.26], saltlake: [-111.89, 40.76], washington: [-77.04, 38.91],
};
const cityXY = Object.fromEntries(Object.entries(CITIES).map(([k, ll]) => [k, proj(ll).map((v) => Math.round(v * 10) / 10)]));

const lines = [
  '// Generated by scripts/build-usmap.mjs from us-atlas (US Census boundaries, Albers USA projection). Do not edit.',
  "import type { StateId } from './states';",
  '',
  'export const MAP_W = 975;',
  'export const MAP_H = 610;',
  '',
  '/** Outline of the whole country (coasts, lakes and borders), for the engraved water lines. */',
  `export const NATION_D = ${JSON.stringify(nation)};`,
  '',
  '/** Each state: SVG path, label point, area in px², atlas tint (0-4, neighbours differ). */',
  'export const STATE_SHAPES: Record<StateId, { d: string; label: [number, number]; area: number; tint: number }> = {',
  ...Object.keys(shapes)
    .sort()
    .map((c) => `  ${c}: { d: ${JSON.stringify(shapes[c].d)}, label: [${shapes[c].label}], area: ${shapes[c].area}, tint: ${tint[c]} },`),
  '};',
  '',
  '/** Where the cities fall on the map. */',
  `export const CITY_XY: Record<string, [number, number]> = ${JSON.stringify(cityXY)};`,
  '',
  '/** States sharing a border. */',
  'export const NEIGHBOURS: Record<StateId, StateId[]> = {',
  ...Object.keys(near)
    .sort()
    .map((c) => `  ${c}: [${[...near[c]].sort().map((n) => `'${n}'`).join(', ')}],`),
  '};',
  '',
];
writeFileSync(new URL('../src/data/usmap.ts', import.meta.url), lines.join('\n'));
console.log(`${Object.keys(shapes).length} states, ${Math.round(lines.join('\n').length / 1024)} KB, tints used: ${Math.max(...Object.values(tint)) + 1}`);
